{
  windowrule = [
    "opacity 0.95 override, fullscreen:0"
    "opaque, class:foot|equibop|org\.quickshell|imv|swappy"
    "center 1, floating:1, xwayland:0"
    "float, class:guifetch"
    "float, class:yad"
    "float, class:zenity"
    "float, class:wev"
    "float, class:org\.gnome\.FileRoller"
    "float, class:file-roller"
    "float, class:blueman-manager"
    "float, class:com\.github\.GradienceTeam\.Gradience"
    "float, class:feh"
    "float, class:imv"
    "float, class:system-config-printer"
    "float, class:org\.quickshell"
    "float, class:foot, title:nmtui"
    "size 60% 70%, class:foot, title:nmtui"
    "center 1, class:foot, title:nmtui"
    "float, class:org\.gnome\.Settings"
    "size 70% 80%, class:org\.gnome\.Settings"
    "center 1, class:org\.gnome\.Settings"
    "float, class:org\.pulseaudio\.pavucontrol|yad-icon-browser"
    "size 60% 70%, class:org\.pulseaudio\.pavucontrol|yad-icon-browser"
    "center 1, class:org\.pulseaudio\.pavucontrol|yad-icon-browser"
    "float, class:nwg-look"
    "size 50% 60%, class:nwg-look"
    "center 1, class:nwg-look"
    "float, title:(Select|Open)( a)? (File|Folder)(s)?"
    "float, title:File (Operation|Upload)( Progress)?"
    "float, title:.* Properties"
    "float, title:Export Image as PNG"
    "float, title:GIMP Crash Debug"
    "float, title:Save As"
    "float, title:Library"
    "move 100%-w-2% 100%-w-3%, title:Picture(-| )in(-| )[Pp]icture"
    "keepaspectratio, title:Picture(-| )in(-| )[Pp]icture"
    "float, title:Picture(-| )in(-| )[Pp]icture"
    "pin, title:Picture(-| )in(-| )[Pp]icture"
    "rounding 10, title:, class:steam"
    "float, title:Friends List, class:steam"
    "immediate, class:steam_app_[0-9]+"
    "idleinhibit always, class:steam_app_[0-9]+"
    "float, class:com-atlauncher-App, title:ATLauncher Console"
    "noblur, title:Fusion360|(Marking Menu), class:fusion360\.exe"
    "nodim, xwayland:1, title:win[0-9]+"
    "noshadow, xwayland:1, title:win[0-9]+"
    "rounding 10, xwayland:1, title:win[0-9]+"
  ];

  windowrulev2 = [
    "noinitialfocus, class:^(.*jetbrains.*)$, title:^(win.*)$"
  ];
}
